#! /bin/bash
#
#export LD_LIBRARY_PATH=/usr/local/lib64

PRG=Main
SUDO=
if [ "$1" = -su ]; then
       SUDO="sudo -E"
       shift
fi

if [ -n "$1" ]; then
       PRG=$1
       shift
fi

if [ ! -x ~ma/bin/sy2l.tcl ]; then
	exec ./$PRG "$@"
fi

LPIPE=LOGFILE

test -p "$LPIPE" || {
        test -e "$LPIPE" && { echo "No pipe '$LPIPE' exists"; exit 1; }
        mkfifo $LPIPE
}
if ! fuser $LPIPE >/dev/null; then
        ~ma/bin/sy2l.tcl $LPIPE &
fi

if ps axl | grep -q '[/]usr/sbin/iceccd'; then
	MAKE="make -j 15"
else
	MAKE="make -j 2"
fi

$MAKE $PRG || exit 1
echo "====================================================="
export ZYPP_LOGFILE=-
export ZYPP_KEYRING_DEFAULT_ACCEPT_ALL=1
export SYSROOT=/Local/ROOT
export ZYPP_CONF=$SYSROOT/zypp.conf

#export ZYPP_TESTSUITE_FAKE_ARCH=x86_64
#$SUDO ./$PRG "$@" 2>&1 | tee log > $LPIPE
exec 2> >(tee log > $LPIPE)
$SUDO ./$PRG "$@"

