#! /bin/bash
#
#export LD_LIBRARY_PATH=/usr/local/lib64

PRG=Main

if [ -n "$1" ]; then
       PRG=$1
       shift
fi

if [ ! -x ~ma/bin/sy2l.tcl ]; then
	exec ./$PRG
fi

LPIPE=LOGFILE

test -p "$LPIPE" || {
        test -e "$LPIPE" && { echo "No pipe '$LPIPE' exists"; exit 1; }
        mkfifo $LPIPE
}
if ! fuser $LPIPE >/dev/null; then
        ~ma/bin/sy2l.tcl $LPIPE &
fi

if ps axl | grep -q '[/]usr/sbin/iceccd'; then
	MAKE="make -j 15"
else
	MAKE=make
fi

$MAKE $PRG || exit 1

export ZYPP_LOGFILE=-
./$PRG "$@" 2> $LPIPE
