'\" t
.\"     Title: locks
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 10/02/2014
.\"    Manual: LIBZYPP
.\"    Source: libzypp
.\"  Language: English
.\"
.TH "LOCKS" "5" "10/02/2014" "libzypp" "LIBZYPP"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
locks \- libzypp locking file
.SH "DESCRIPTION"
.sp
The file \fI/etc/zypp/locks\fR is read by libzypp at start\-up if \fIzypp\&.conf\fR allows it\&. The entries are used for initial locking of packages\&. Locking a package means not allowing to install or uninstall it\&.
.sp
Valid entries are of the form:
.PP
\fIattribute\fR\fB:\fR \fIvalue\fR
.RS 4
Where attributes and their values are described below\&.
.RE
.sp
Locks are separated by an empty lines\&.
.SH "ATTRIBUTES"
.sp
All attributes are lower\-case\&.
.PP
\fBrepo\fR
.RS 4
specifies repository restriction\&. Only alias is accepted\&.

By default all repositories match\&.
.RE
.PP
\fBtype\fR
.RS 4
resolvable type restriction\&. The values can be
\fBpackage\fR,
\fBpatch\fR,
\fBpattern\fR,
\fBproduct\fR
and
\fBsrcpackage\fR\&.

By default all types match\&.
.RE
.PP
\fBcase_sensitive\fR
.RS 4
if strings are matched case sensitive\&. The values are
\fBtrue\fR,
\fBfalse\fR,
\fBon\fR,
\fBoff\fR\&.

The default is case insensitive\&.
.RE
.PP
\fBinstall_status\fR
.RS 4
status of object\&. Possible states are
\fBinstalled\fR,
\fBnot\-installed\fR
and
\fBall\fR\&. If more install statuses are specified then the last one is used\&. The values are
\fBinstalled\fR
for all packages which are installed,
\fBnon\-installed\fR
for packages which can be installed or reinstalled and
\fBall\fR
for both\&.

The default is
\fBall\fR\&.
.RE
.PP
\fBmatch_type\fR
.RS 4
type of string matching in values\&. Does not affect
\fBtype\fR
and
\fBrepo\fR
which must be specified exactly\&. The values are
\fBexact\fR,
\fBsubstring\fR,
\fBregex\fR
for regular expressions,
\fBglob\fR
for matching as on the command line, and
\fBword\fR\&.

The default is
\fBsubstring\fR\&.
.RE
.PP
\fBquery_string\fR
.RS 4
String to be matched in multiple attributes\&. Should be restricted by another attribute with empty value (it is recommended, because without restriction expect some performance problems)\&.
.RE
.PP
\fBversion\fR
.RS 4
Restrict the lock only to some versions\&. It contains two parts: an optional operator and the version\&.

The operator is
\fB==\fR,
\fB!=\fR,
\fB<\fR,
\fB>\fR,
\fB⇐\fR,
\fB>=\fR\&. If operator is not specified then
\fB==\fR
is used\&.

The version has the format [\fIepoch\fR\fB:\fR]\fIversion\fR[\fB\-\fR\fIrelease\fR]\&.

Example:
\fBversion: < 0:0\&.11\&.4\-2\fR
.RE
.PP
\fBsolvable_name\fR
.RS 4
name of object (e\&.g\&. zypper)
.RE
.PP
\fBsolvable_summary\fR
.RS 4
summary of object
.RE
.PP
\fBsolvable_arch\fR
.RS 4
architecture of object (e\&.g\&. x86_64, i586)
.RE
.PP
\fBsolvable_description\fR
.RS 4
description of object
.RE
.PP
\fBsolvable_eula\fR
.RS 4
license text of objects which request accepting license by user
.RE
.PP
\fBsolvable_license\fR
.RS 4
license of package (only for package) (e\&.g\&. GPL2)
.RE
.PP
\fBsolvable_keywords\fR
.RS 4
keywords which specify package (only for package)
.RE
.PP
\fBsolvable_authors\fR
.RS 4
authors of package (only for package)
.RE
.PP
\fBsolvable_group\fR
.RS 4
package group (only for package) (e\&.g\&. Development/Tools/Version Control )
.RE
.PP
\fBupdate_reference_type\fR
.RS 4
reference for update (e\&.g\&. bugzilla,cve) (only for patches)
.RE
.SH "EXAMPLES"
.PP
\fBExact Package\fR
.RS 4
This is the way YaST UI does it\&. Lock k3b (e\&.g\&. you don\(cqt want to update it)\&.
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-\-\-\-locks\-\-\-\-\-
type: package
solvable_name: k3b
match_type: exact
case_sensitive: on
.fi
.if n \{\
.RE
.\}
.PP
\fBPackage Wildcard\fR
.RS 4
This is the way "zypper addlock cross\-*\-gcc\-icecream\-backend" does it\&.
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-\-\-\-locks\-\-\-\-\-
type: package
solvable_name: cross\-*\-gcc\-icecream\-backend
match_type: glob
case_sensitive: on
.fi
.if n \{\
.RE
.\}
.PP
\fBVersioned Lock\fR
.RS 4
Do not install new GCC\&. This format is used when converting from the openSUSE\-10\&.3 lock format\&.
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-\-\-\-locks\-\-\-\-\-
solvable_name: gcc
match_type: glob
version: > 4\&.2
.fi
.if n \{\
.RE
.\}
.PP
\fBAnything named KDE\fR
.RS 4
Locks everything which contains kde in the name\&.
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-\-\-\-locks\-\-\-\-\-
solvable_name: kde
.fi
.if n \{\
.RE
.\}
.PP
\fBAnything mentioning KDE\fR
.RS 4
Locks everything which contains kde in the name, summary, or description\&.
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
\-\-\-\-\-locks\-\-\-\-\-
query_string: kde
solvable_name:
solvable_summary:
solvable_description:
.fi
.if n \{\
.RE
.\}
.SH "HOMEPAGE"
.sp
This manual page only covers the most important attributes\&. The complete list is available at http://en\&.opensuse\&.org/Libzypp/Locksfile
.SH "AUTHORS"
.sp
Josef Reidinger <jreidinger@suse\&.cz> Manual page contributions by Martin Vidner <mvidner@suse\&.cz>\&.
.SH "SEE ALSO"
.sp
zypper(8)
