print "Build libpdbtozypp.so\n";
`make -f Makefile.no`;
print "Install libpdbtozypp.so\n";
`make -f Makefile.no install`;
print "Build swig-binding\n";
`make -f Makefile.no swig`;
print "Build Makefile for perl-module with MakeMaker\n";
`perl Makefile.PL`;
print "Build perl-module\n";
`make`;
print "Install perl-module\n";
`make install`;
