/*
 * mkarray - make a c array containing the input file.
 *
 * this file is part of the makeutil package:
 *   http://sourceforge.net/projects/makeutil/
 *   http://www.cybermesa.com/~aisa/makeutil/
 *
 * this file is hereby placed in the public domain.
 * aisa0@users.sourceforge.net, aisa@cybermesa.com
 */

static char rcsid[]="$Id: mkarray.c,v 1.2 2004/12/11 18:21:51 aisa0 Exp $";

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static
mkarray(filename, file, ofile, varname)
  char *filename;
  FILE *file;
  FILE *ofile;
  char *varname;
{
  char buf[BUFSIZ];
  size_t i, rsize, tsize=0;
  int done=0, line=8, status=EXIT_SUCCESS;

  fprintf(ofile, "/*\n");
  fprintf(ofile, " * this file is automatically generated\n");
  fprintf(ofile, " */\n");
  fprintf(ofile, "\n");
  fprintf(ofile, "#include <string.h>\n");
  fprintf(ofile, "\n");
  fprintf(ofile, "static char rcsid[]=\"%s\";\n", rcsid);
  fprintf(ofile, "\n");
  fprintf(ofile, "char %s[]=\n{\n", varname);

  while(!done) {
    int i, ch;

    rsize=fread(&buf[0], sizeof(char), sizeof buf/sizeof buf[0], file);
    tsize+=rsize;

    switch(rsize) {
    case 0:
      rsize=1;
      buf[0]='\0';
      done=1;

      /* down seems more likely */

    default:
      for(i=0;i<rsize;++i) {
        if(8==line) fputc('\t', ofile);

        line+=(ch=fprintf(ofile, "0x%02x,", buf[i]&0xff));

        if(line+ch>=78) {
          line=8;
          fputc('\n', ofile);
        }
      }
    }
  }
  if(ferror(file)) {
    perror("error: read");
    status|=EXIT_FAILURE;
  }

  if(8!=line) fputc('\n', ofile);
  fputs("};\n\n", ofile);

  fprintf(ofile, "size_t _%s_size=%d;\n", varname, tsize);
  fprintf(ofile, "size_t *%s_size=&_%s_size;\n", varname, varname);

  if(ferror(ofile)) {
    perror("error: write: -: ");
    status|=EXIT_FAILURE;
  }
  if(EOF==fclose(ofile)) {
    perror("error: close: -: ");
    status|=EXIT_FAILURE;
  }

  return status;
}

main(argc, argv)
  char *argv[];
{
  char *filename, *ofilename, *varname;
  FILE *file;
  int status=EXIT_SUCCESS;

  --argc;
  ++argv;

  if(argc!=3) {
      fputs("usage: mkarray <input-file> <var-name> <output-file>\n", stderr);
      fprintf( stderr, "You gave %d args\n", argc);
      exit(status|EXIT_FAILURE);
  }

  filename=argv[0];
  ofilename=argv[2];
  varname=argv[1];

  if(0==strcmp("-", filename)) {
    status|=mkarray(filename, stdin, varname);
  } else {
    FILE *file;
    FILE *ofile;
    if( ( NULL!=(file=fopen(filename, "rb")) ) && ( NULL!=(ofile=fopen(ofilename, "w")) ) )
    {
      status|=mkarray(filename, file, ofile, varname);
      if(EOF==fclose(file)) {
        perror("error: close");
        status|=EXIT_FAILURE;
      }
    }
    else
    {
      perror("error: open");
      status|=EXIT_FAILURE;
    }
  }

  exit(status);
}

/*                                                              ..__
 *                                                              `' "
 */
