#
# parser_yum.exp
# 'main' file for all YUM parser tests
#
# Runs all tests with the extention "xml" for all their data.
#
# Each testprogram <programname>.multi has an own subdirectory
# data.<programmname> in which several subdirectories with test-
# cases are defined for this program.
# Each of these testcase has 2 files:
#
#	*-test.xml
#	*-test.solution
#
# The program "<programname>.multi" will be called with the argument
# "...-test.xml" and its output redirected to "...-test.mistake".
# The "...-test.mistake" is then diffed to the "...solution" file
# generating a "...diff" file.
#
# The testcase is successful if the program returns 0 AND
# the "...diff" file is empty
#
# Additionally, if a subdirectory contains the file "xfail",
# it is supposed to contain the filename of testcases which
# are expected to fail
#
#
  return

#if { [catch {  set filenames [glob $srcdir/tests/*.xml] } ] } {
#    puts "No .xml files found"
#} else {
#    # foreach file, call multi-run (from testsuite/lib)
#
#    foreach file $filenames { runYumTest $file }
#}
