
#ifndef SQLITE_SOURCE_SCHEMA_H
#define SQLITE_SOURCE_SCHEMA_H

#define PACKAGES_TABLE_COLUMN_SIZE_INSTALLED 6
#define PACKAGES_TABLE_COLUMN_GROUP 10
#define PACKAGES_TABLE_COLUMN_SIZE_ARCHIVE 11
#define PACKAGES_TABLE_COLUMN_SUMMARY 12
#define PACKAGES_TABLE_COLUMN_DESCRIPTION 13
#define PACKAGES_TABLE_COLUMN_PACKAGE_URL 14
#define PACKAGES_TABLE_COLUMN_PACKAGE_FILENAME 15
#define PACKAGES_TABLE_COLUMN_INSTALL_ONLY 16
#define PACKAGES_TABLE_COLUMN_MEDIA_NR 17

#define PATCHES_TABLE_COLUMN_ID 0
#define PATCHES_TABLE_COLUMN_NAME 1
#define PATCHES_TABLE_COLUMN_VERSION 2
#define PATCHES_TABLE_COLUMN_RELEASE 3
#define PATCHES_TABLE_COLUMN_EPOCH 4
#define PATCHES_TABLE_COLUMN_ARCH 5
#define PATCHES_TABLE_COLUMN_SIZE_INSTALLED 6
#define PATCHES_TABLE_COLUMN_PATCH_ID 10
#define PATCHES_TABLE_COLUMN_TIMESTAMP 12
#define PATCHES_TABLE_COLUMN_CATEGORY 13
#define PATCHES_TABLE_COLUMN_REBOOT_NEEDED 14
#define PATCHES_TABLE_COLUMN_AFFECTS_PACKAGE_MANAGER 15
#define PATCHES_TABLE_COLUMN_INTERACTIVE 16

#define PATTERNS_TABLE_COLUMN_ID 0
#define PATTERNS_TABLE_COLUMN_NAME 1
#define PATTERNS_TABLE_COLUMN_VERSION 2
#define PATTERNS_TABLE_COLUMN_RELEASE 3
#define PATTERNS_TABLE_COLUMN_EPOCH 4
#define PATTERNS_TABLE_COLUMN_ARCH 5

#define PRODUCTS_TABLE_COLUMN_CATEGORY 7

#endif