#!/bin/bash
SOURCE_DIR="${1:-..}"
POTFILE="${2:-po/zypp.pot}"
# search for sourcecode-files
cd "$SOURCE_DIR"
SRCFILES=`find examples tools zypp \
                           -type f -name "*.h" \
                                -o -name "*.pm"  \
                                -o -name "*.c"   \
                                -o -name "*.cc"  \
                                -o -name "*.cpp"`
#calling xgettext with the sourcefiles
xgettext -L C++ --boost -s --no-wrap --add-comments --add-location --keyword=_ --keyword=_:1,2 --keyword=__ --keyword=N_ --keyword=PL_:1,2 --foreign-user --copyright-holder="SuSE Linux GmbH, Nuernberg" --package-name=libzypp --default-domain=libzypp --output="$POTFILE" $SRCFILES
