#!/bin/bash
SOURCE_DIR="${1:-..}"
POTFILE="${2:-po/zypper.pot}"

# search for sourcecode-files
cd "$SOURCE_DIR"
SRCFILES=`find src \
                           -type f -name "*.h" \
                                -o -name "*.pm"  \
                                -o -name "*.c"   \
                                -o -name "*.cc"  \
                                -o -name "*.cpp"`

#calling xgettext with the sourcefiles
xgettext --no-wrap --add-comments --add-location --keyword=_ --keyword=_:1,2 --keyword=__ --keyword=N_ --keyword=_PL:1,2 --foreign-user --copyright-holder="SuSE Linux Products GmbH, Nuernberg" --default-domain=zypper --output="$POTFILE" $SRCFILES
