
SET( UDEV_LIBRARY )
SET( UDEV_INCLUDE_DIR )

FIND_PATH( UDEV_INCLUDE_DIR libudev.h
	/usr/include
	/usr/local/include
)

FIND_LIBRARY( UDEV_LIBRARY NAMES udev
	PATHS
	/usr/lib
	/usr/local/lib
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS( Udev DEFAULT_MSG UDEV_LIBRARY UDEV_INCLUDE_DIR )
MARK_AS_ADVANCED(  UDEV_LIBRARY UDEV_INCLUDE_DIR )
