
if(CURL_INCLUDE_DIR AND CURL_LIBRARY)
	# Already in cache, be silent
	set(CURL_FIND_QUIETLY TRUE)	
endif(CURL_INCLUDE_DIR AND CURL_LIBRARY)

set(CURL_LIBRARY)
set(CURL_INCLUDE_DIR)

FIND_PATH(CURL_INCLUDE_DIR curl/curl.h
	/usr/include
	/usr/local/include
)

FIND_LIBRARY(CURL_LIBRARY NAMES curl
	PATHS
	/usr/lib
	/usr/local/lib
)

if(CURL_INCLUDE_DIR AND CURL_LIBRARY)
   MESSAGE( STATUS "curl found: includes in ${CURL_INCLUDE_DIR}, library in ${CURL_LIBRARY}")
   set(CURL_FOUND TRUE)
else(CURL_INCLUDE_DIR AND CURL_LIBRARY)
   MESSAGE( STATUS "curl not found")
endif(CURL_INCLUDE_DIR AND CURL_LIBRARY)

MARK_AS_ADVANCED(CURL_INCLUDE_DIR CURL_LIBRARY)