
if(LIBXML_INCLUDE_DIR AND LIBXML_LIBRARY)
	# Already in cache, be silent
	set(LIBXML_FIND_QUIETLY TRUE)	
endif(LIBXML_INCLUDE_DIR AND LIBXML_LIBRARY)

set(LIBXML_LIBRARY)
set(LIBXML_INCLUDE_DIR)

FIND_PATH(LIBXML_INCLUDE_DIR libxml/parser.h
	/usr/include
	/usr/include/libxml2
	/usr/local/include
)

FIND_LIBRARY(LIBXML_LIBRARY NAMES xml2
	PATHS
	/usr/lib
	/usr/local/lib
)

if(LIBXML_INCLUDE_DIR AND LIBXML_LIBRARY)
   MESSAGE( STATUS "libxml found: includes in ${LIBXML_INCLUDE_DIR}, library in ${LIBXML_LIBRARY}")
   set(LIBXML_FOUND TRUE)
else(LIBXML_INCLUDE_DIR AND LIBXML_LIBRARY)
   MESSAGE( STATUS "libxml not found")
endif(LIBXML_INCLUDE_DIR AND LIBXML_LIBRARY)

MARK_AS_ADVANCED(LIBXML_INCLUDE_DIR LIBXML_LIBRARY)