INCLUDE( ${CMAKE_ROOT}/Modules/UsePkgConfig.cmake)
PKGCONFIG("dbus-glib-1" DBUS_GLIB_INCLUDE_DIR DBUS_GLIB_LINK_DIR DBUS_GLIB_LINK_FLAGS DBUS_GLIB_CFLAGS)

IF(DBUS_GLIB_CFLAGS)
  SET(DBUS_GLIB_FOUND TRUE)
ENDIF(DBUS_GLIB_CFLAGS)