
if(SQLITE_INCLUDE_DIR AND SQLITE_LIBRARY)
	# Already in cache, be silent
	set(SQLITE_FIND_QUIETLY TRUE)	
endif(SQLITE_INCLUDE_DIR AND SQLITE_LIBRARY)

set(SQLITE_LIBRARY)
set(SQLITE_INCLUDE_DIR)

FIND_PATH(SQLITE_INCLUDE_DIR sqlite3.h
	/usr/include
	/usr/local/include
)

FIND_LIBRARY(SQLITE_LIBRARY NAMES sqlitezmd3 sqlite3
	PATHS
	/usr/lib
	/usr/local/lib
)

if(SQLITE_INCLUDE_DIR AND SQLITE_LIBRARY)
   MESSAGE( STATUS "sqlite found: includes in ${SQLITE_INCLUDE_DIR}, library in ${SQLITE_LIBRARY}")
   set(SQLITE_FOUND TRUE)
else(SQLITE_INCLUDE_DIR AND SQLITE_LIBRARY)
   MESSAGE( STATUS "sqlite not found")
endif(SQLITE_INCLUDE_DIR AND SQLITE_LIBRARY)

MARK_AS_ADVANCED(SQLITE_INCLUDE_DIR SQLITE_LIBRARY)