#!/usr/bin/perl -w
use strict;

my $pattern=shift;
my $solvdir="/var/cache/zypp/solv";
open(my $cnf, "/etc/zypp/zypp.conf") or die "zypp.conf: $!";
while(<$cnf>) {
  if(m/^cachedir = (.*)/) {$solvdir="$1/solv"}
  if(m/^solvfilesdir = (.*)/) {$solvdir=$1}
}
chdir($solvdir) or die;
my @idx=<*/solv.idx> or die "no solv.idx files";
open(my $pipe, "-|", "grep", "--with-filename", "--", $pattern, @idx) or die $!;

print "Name\t\tVersion\t\tArch\tRepository\n" if -t STDOUT;
while(<$pipe>) {
	chop;
	s{^([^/]+)/solv.idx:}{};
	print "$_\t$1\n";
}

